stages:
  - build
  - deploy

build-code-job:
  stage: build
  image: node:18-buster
  script:
    - echo Building express-hello-world

deploy-code-job:
  stage: deploy
  image: node:18-buster
  variables:
    GITHUB_URL: git@github.com:JorriFransen/express-hello-world.git
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval `ssh-agent -s`
    - ssh-add <(echo "$PRIVATE_SSH_KEY")
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  script:
    - git remote add github "$GITHUB_URL"
    - git fetch github
    - git checkout github/main
    - git merge "origin$CI_COMMIT_BRANCH"
    - echo "$CI_DEFAULT_BRANCH"
    - git push github HEAD:main
